// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kol2.Entities;

namespace kol2.Migrations
{
    [DbContext(typeof(FireStationContext))]
    [Migration("20220530183427_Data")]
    partial class Data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("kol2.Entities.Action", b =>
                {
                    b.Property<int>("IdAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NeedSpecialEquipment")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("IdAction")
                        .HasName("Action_pk");

                    b.ToTable("Action");

                    b.HasData(
                        new
                        {
                            IdAction = 1,
                            EndTime = new DateTime(2022, 6, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            NeedSpecialEquipment = true,
                            StartTime = new DateTime(2022, 5, 30, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            IdAction = 2,
                            EndTime = new DateTime(2022, 4, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            NeedSpecialEquipment = false,
                            StartTime = new DateTime(2022, 2, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            IdAction = 3,
                            EndTime = new DateTime(2021, 8, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            NeedSpecialEquipment = false,
                            StartTime = new DateTime(2021, 8, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            IdAction = 4,
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NeedSpecialEquipment = true,
                            StartTime = new DateTime(2021, 12, 31, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("kol2.Entities.FireTruck", b =>
                {
                    b.Property<int>("IdFiretruck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OperationNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("SpecialEquipment")
                        .HasColumnType("bit");

                    b.HasKey("IdFiretruck")
                        .HasName("FireTruck_pk");

                    b.ToTable("FireTruck");

                    b.HasData(
                        new
                        {
                            IdFiretruck = 1,
                            OperationNumber = "1234",
                            SpecialEquipment = false
                        },
                        new
                        {
                            IdFiretruck = 2,
                            OperationNumber = "420",
                            SpecialEquipment = true
                        },
                        new
                        {
                            IdFiretruck = 3,
                            OperationNumber = "9999",
                            SpecialEquipment = false
                        },
                        new
                        {
                            IdFiretruck = 4,
                            OperationNumber = "12455136",
                            SpecialEquipment = true
                        });
                });

            modelBuilder.Entity("kol2.Entities.FireTruckAction", b =>
                {
                    b.Property<int>("IdFiretruck")
                        .HasColumnType("int");

                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdFiretruck", "IdAction")
                        .HasName("FireTruckAction_pk");

                    b.HasIndex("IdAction");

                    b.ToTable("FireTruck_Action");

                    b.HasData(
                        new
                        {
                            IdFiretruck = 1,
                            IdAction = 1,
                            AssignmentDate = new DateTime(2022, 5, 30, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            IdFiretruck = 2,
                            IdAction = 1,
                            AssignmentDate = new DateTime(2022, 5, 30, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            IdFiretruck = 3,
                            IdAction = 1,
                            AssignmentDate = new DateTime(2022, 5, 30, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            IdFiretruck = 1,
                            IdAction = 2,
                            AssignmentDate = new DateTime(2022, 2, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            IdFiretruck = 1,
                            IdAction = 3,
                            AssignmentDate = new DateTime(2021, 8, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            IdFiretruck = 2,
                            IdAction = 3,
                            AssignmentDate = new DateTime(2021, 8, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            IdFiretruck = 3,
                            IdAction = 4,
                            AssignmentDate = new DateTime(2021, 12, 31, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            IdFiretruck = 4,
                            IdAction = 4,
                            AssignmentDate = new DateTime(2021, 12, 31, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("kol2.Entities.FireTruckAction", b =>
                {
                    b.HasOne("kol2.Entities.Action", "IdActionNavigation")
                        .WithMany("FireTruckActions")
                        .HasForeignKey("IdAction")
                        .HasConstraintName("FireTruckAction_Action")
                        .IsRequired();

                    b.HasOne("kol2.Entities.FireTruck", "IdFireTruckNavigation")
                        .WithMany("FireTruckActions")
                        .HasForeignKey("IdFiretruck")
                        .HasConstraintName("FireTruckAction_FireTruck")
                        .IsRequired();

                    b.Navigation("IdActionNavigation");

                    b.Navigation("IdFireTruckNavigation");
                });

            modelBuilder.Entity("kol2.Entities.Action", b =>
                {
                    b.Navigation("FireTruckActions");
                });

            modelBuilder.Entity("kol2.Entities.FireTruck", b =>
                {
                    b.Navigation("FireTruckActions");
                });
#pragma warning restore 612, 618
        }
    }
}
